import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	define: {
		/* build stamp for the settings header + load log (see src/buildInfo.ts) */
		__OA_BUILD_STAMP__: JSON.stringify(
			new Date().toISOString().slice(0, 16).replace("T", " ") + "Z"
		),
		/* manifest version baked in for `/version` (v0.1.20) */
		__OA_VERSION__: JSON.stringify(JSON.parse(readFileSync("manifest.json", "utf8")).version),
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		/* pdfjs-dist references node-canvas only in its Node branch
		   (NodeCanvasFactory) — unreachable inside Obsidian (Electron
		   renderer is explicitly !isNodeJS, line ~68 of build/pdf.js) */
		"canvas",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	/* v0.1.128 (audit 2026-08-09 docs/audits/audit-2026-08-09.md): production build
	   TIDAK PERNAH di-minify — plugin dikirim 5,40 MB tersusun-rapi padahal
	   Obsidian mengeksekusinya apa adanya. Dry-run metafile: 5.398.228 B →
	   1.926.827 B (−64,3%). Dev/inline sourcemap tak terpengaruh. JANGAN
	   tambahkan opsi yang melempar pernyataan log — jalur debugMode sengaja
	   menjaga console.* nya. */
	minify: prod ? true : false,
	treeShaking: true,
	jsx: "automatic",
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	/* v0.1.130: vendor pdf.worker dieksternalisasi — file regenerable di
	   setiap build production supaya zip rilis tak pernah kehilangan dia
	   (scripts/build-vendor.mjs; src/ui/attach/pdf.ts memuatnya runtime) */
	const { buildVendorFile } = await import("./scripts/build-vendor.mjs");
	await buildVendorFile();
	process.exit(0);
} else {
	await context.watch();
}
