/**
 * Structured memory engine (v0.1.176, Fase 1) — a Hindsight-style typed
 * memory system, rewritten plugin-native: no Docker, no MCP, no server.
 *
 * What it borrows (docs/studies/memory-context-engine-research-2026-08-21.md):
 *   · Hindsight   — world/experience facts + multi-strategy recall fusion
 *                   (BM25 + entity + temporal) + the injection preamble.
 *   · Mem0        — LLM extraction that decides typed ops (add/update/delete)
 *                   in ONE call, with automatic deduplication.
 *   · Holographic — per-fact trust score (0..1) folded into ranking.
 *   · Letta/MemGPT — "core vs archival" split: MEMORY.md/USER.md stay the
 *                   always-visible core; this engine is the on-demand
 *                   archival layer that is recalled per message.
 *
 * Honest divergence from full Hindsight: no vector embeddings and no
 * cross-encoder reranker (both need a separate server/model). Retrieval is
 * BM25 + entity overlap + temporal decay + trust — all pure TypeScript, zero
 * latency. An optional embedding/rerank pass may join in a later phase.
 *
 * This module is split in two halves:
 *   · pure functions (below the store) — node-testable, no Obsidian import.
 *   · EngineMemoryStore — the vault-file adapter (facts.jsonl).
 */

import { App } from "obsidian";
import { canonicalVaultPath, pathContains } from "./workspacePolicy";
import { firstThreatMessage } from "./threatPatterns";

/* ── types ──────────────────────────────────────────────────────────────── */

export type FactKind = "world" | "experience";

export interface EngineFact {
	/** stable id; generated by the store ("f-<ts>-<seq>") */
	id: string;
	kind: FactKind;
	/** the fact itself, one concise sentence */
	text: string;
	/** proper names / keys the fact is about (from LLM extraction) */
	entities: string[];
	/** 0..1 — starts at 0.5; raised/lowered by feedback (Holographic trust) */
	trust: number;
	createdAt: number;
	updatedAt: number;
}

export type RetainOp =
	| { op: "add"; kind: FactKind; text: string; entities: string[] }
	| { op: "update"; id: string; text: string }
	| { op: "delete"; id: string };

export interface RetainCounts {
	added: number;
	updated: number;
	deleted: number;
}

/** Minimal LLM bridge — the caller wraps chatCompletion (main/aux model). */
export type EngineLLM = (
	messages: { role: string; content: string }[],
	signal?: AbortSignal
) => Promise<string>;

export const MAX_ENGINE_FACTS = 500;

/* ── Fase 2: observations + mental models (reflect) ─────────────────────── */

/** Consolidated belief grounded in facts — keeps its evidence (Hindsight
 *  observation: proof quotes + proof count, refined rather than overwritten). */
export interface EngineObservation {
	id: string;
	text: string;
	/** ids of the facts this observation is grounded in (evidence) */
	factIds: string[];
	/** exact supporting quotes (evidence) */
	proofs: string[];
	proofCount: number;
	trust: number;
	createdAt: number;
	updatedAt: number;
}

/** A standing answer to a standing question (Hindsight mental model) — read
 *  as a pure file read, no LLM at retrieval time. */
export interface EngineMentalModel {
	id: string;
	question: string;
	answer: string;
	updatedAt: number;
}

/** Reflect bookkeeping: when we last consolidated and how many facts existed. */
export interface EngineMeta {
	lastReflectAt: number;
	factCountAtReflect: number;
}

/** Built-in standing questions the consolidator answers from observations. */
export const MENTAL_MODEL_QUESTIONS: string[] = [
	"What are the user's durable preferences and working style?",
	"What is the current state of the user's main project(s)?",
	"What decisions or conventions has the user locked in?",
	"What recurring pain points or gotchas does the user keep hitting?",
];

export const MAX_ENGINE_OBSERVATIONS = 200;
export const MAX_ENGINE_MODELS = 20;

/* ── trivial-prompt gate (Hermes TRIVIAL_PROMPT_RE parity) ─────────────── */

const TRIVIAL_PROMPT_RE = new RegExp(
	"^(yes|no|ok|okay|sure|thanks|thank you|y|n|yep|nope|yeah|nah|" +
		"hi|hey|hello|yo|sup|" +
		"continue|go ahead|do it|proceed|got it|cool|nice|great|done|next|lgtm|k)" +
		"[\\s!?.:,;\"'~\\u2018\\u2019\\u201c\\u201d\\u2014\\u2013\\u2026()\\[\\]{}<>*&^%$#@!+=`\\u00a0]*$",
	"i"
);

/** True for greetings/acks/slash-commands — no recall/retain value. */
export function isTrivialPrompt(text: string | null | undefined): boolean {
	if (!text) return true;
	const stripped = text.trim();
	if (!stripped) return true;
	if (stripped.startsWith("/")) return true;
	return TRIVIAL_PROMPT_RE.test(stripped);
}

/* ── text helpers ───────────────────────────────────────────────────────── */

export function tokenize(text: string): string[] {
	return (text.toLowerCase().match(/[a-z0-9]+/g) ?? []).filter((t) => t.length >= 2);
}

/** Canonical dedupe key: lowercase, alnum tokens collapsed. */
export function factKey(text: string): string {
	return text
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, " ")
		.trim()
		.split(/\s+/)
		.join(" ");
}

function clamp01(n: number): number {
	return Number.isFinite(n) ? Math.min(1, Math.max(0, n)) : 0.5;
}

/* ── BM25 ──────────────────────────────────────────────────────────────── */

function termFreq(tokens: string[]): Map<string, number> {
	const m = new Map<string, number>();
	for (const t of tokens) m.set(t, (m.get(t) ?? 0) + 1);
	return m;
}

/** Simplified BM25 over a corpus of token lists (k1=1.5, b=0.75). */
export function bm25(queryTokens: string[], docTokens: string[], corpus: string[][]): number {
	if (queryTokens.length === 0 || docTokens.length === 0 || corpus.length === 0) return 0;
	const k1 = 1.5;
	const b = 0.75;
	const avgdl = corpus.reduce((s, d) => s + d.length, 0) / corpus.length;
	const tf = termFreq(docTokens);
	const df = new Map<string, number>();
	for (const d of corpus) for (const t of new Set(d)) df.set(t, (df.get(t) ?? 0) + 1);
	let score = 0;
	for (const t of new Set(queryTokens)) {
		const f = tf.get(t) ?? 0;
		if (f === 0) continue;
		const n = df.get(t) ?? 0;
		const idf = Math.log(1 + (corpus.length - n + 0.5) / (n + 0.5));
		score += (idf * (f * (k1 + 1))) / (f + k1 * (1 - b + b * (docTokens.length / avgdl)));
	}
	return score;
}

/* ── scoring fusion ─────────────────────────────────────────────────────── */

/** Count of the fact's entities that appear in the (lowercased) query. */
export function entityOverlap(queryLower: string, fact: EngineFact): number {	if (fact.entities.length === 0) return 0;
	let hits = 0;
	for (const e of fact.entities) {
		if (e && queryLower.includes(e.toLowerCase())) hits++;
	}
	return hits;
}

/** Recency weight — half-life of 30 days. */
export function temporalWeight(updatedAt: number, now: number, halfLifeDays = 30): number {
	const ageDays = Math.max(0, (now - updatedAt) / 86_400_000);
	return Math.pow(0.5, ageDays / halfLifeDays);
}

export interface RankedFact {
	fact: EngineFact;
	score: number;
}

/** Fuse BM25 + entity overlap + recency, scaled by trust. Zero-latency. */
export function rankFacts(query: string, facts: EngineFact[], now: number, limit = 8): RankedFact[] {
	const ql = query.toLowerCase();
	const queryTokens = tokenize(query);
	const corpus = facts.map((f) => tokenize(f.text));
	return facts
		.map((fact) => {
			const b = bm25(queryTokens, tokenize(fact.text), corpus);
			const e = entityOverlap(ql, fact);
			const t = temporalWeight(fact.updatedAt, now);
			const trust = clamp01(fact.trust);
			const score = (Math.log1p(b) * 3 + e * 2.5 + t) * (0.5 + trust * 0.5);
			return { fact, score };
		})
		.filter((r) => r.score > 0)
		.sort((a, b) => b.score - a.score)
		.slice(0, limit);
}

/** v0.1.178 (Fase 3): an embedding provider — one vector per input (null for
 *  a missing entry), or null on failure. Optional; recall falls back to pure
 *  fusion when absent. */
export type EmbedFn = (texts: string[]) => Promise<(number[] | null)[] | null>;

/** Cosine similarity in [0..1]; 0 on empty/zero-norm vectors. */
export function cosineSimilarity(a: number[], b: number[]): number {
	if (!a || !b || a.length === 0 || b.length === 0 || a.length !== b.length) return 0;
	let dot = 0;
	let na = 0;
	let nb = 0;
	for (let i = 0; i < a.length; i++) {
		dot += a[i] * b[i];
		na += a[i] * a[i];
		nb += b[i] * b[i];
	}
	if (na === 0 || nb === 0) return 0;
	return Math.max(0, dot / (Math.sqrt(na) * Math.sqrt(nb)));
}

/** Re-rank already-scored candidates with semantic similarity: score is
 *  multiplied by (1 + cosine), so a strong lexical hit stays, and a near-
 *  synonym that BM25 missed can climb. Pure of transport (embed injected). */
export async function fuseScores<T extends { score: number }>(
	query: string,
	ranked: T[],
	textOf: (r: T) => string,
	embed: EmbedFn
): Promise<T[]> {
	if (ranked.length === 0) return ranked;
	const vecs = await embed([query, ...ranked.map(textOf)]);
	if (!vecs || !vecs[0]) return ranked;
	const q = vecs[0];
	return ranked
		.map((r, i) => {
			const v = vecs[i + 1];
			if (!v) return r;
			const c = cosineSimilarity(q, v);
			return { ...r, score: r.score * (1 + c) };
		})
		.sort((a, b) => b.score - a.score);
}

export interface RankedObservation {
	obs: EngineObservation;
	score: number;
}

/** BM25 + recency + trust over observation texts (observations carry no
 *  entities — they are consolidated prose). */
export function rankObservations(query: string, observations: EngineObservation[], now: number, limit = 4): RankedObservation[] {
	const queryTokens = tokenize(query);
	const corpus = observations.map((o) => tokenize(o.text));
	return observations
		.map((obs) => {
			const b = bm25(queryTokens, tokenize(obs.text), corpus);
			const t = temporalWeight(obs.updatedAt, now);
			const trust = clamp01(obs.trust);
			const score = (Math.log1p(b) * 3 + t) * (0.5 + trust * 0.5);
			return { obs, score };
		})
		.filter((r) => r.score > 0)
		.sort((a, b) => b.score - a.score)
		.slice(0, limit);
}

/* ── contradiction hint (Holographic) ──────────────────────────────────── */

const NEG_WORDS = ["not", "no", "never", "don't", "dont", "doesn't", "doesnt", "dislike", "dislikes", "hate", "hates", "stop", "stopped", "without"];

const negWordRe = (w: string) => new RegExp(`\\b${w}\\b`, "i");

/** Cheap lexical negation-flip heuristic: one negated, the other not, with
 *  ≥2 significant words in common. Used as a reconcile hint, not a verdict —
 *  the LLM decides update/delete during retain. */
export function contradicts(a: string, b: string): boolean {
	const na = NEG_WORDS.some((w) => negWordRe(w).test(a));
	const nb = NEG_WORDS.some((w) => negWordRe(w).test(b));
	if (na === nb) return false;
	const negSet = new Set(NEG_WORDS);
	const wa = new Set(tokenize(a).filter((w) => !negSet.has(w)));
	const wb = new Set(tokenize(b).filter((w) => !negSet.has(w)));
	let overlap = 0;
	for (const w of wa) if (wb.has(w)) overlap++;
	return overlap >= 2;
}

/* ── JSONL (facts file) ────────────────────────────────────────────────── */

function validFact(f: unknown): f is EngineFact {
	if (!f || typeof f !== "object" || Array.isArray(f)) return false;
	const o = f as Record<string, unknown>;
	return (
		typeof o.id === "string" &&
		(o.kind === "world" || o.kind === "experience") &&
		typeof o.text === "string" &&
		o.text.trim().length > 0 &&
		Array.isArray(o.entities) &&
		typeof o.trust === "number" &&
		typeof o.createdAt === "number" &&
		typeof o.updatedAt === "number"
	);
}

export function parseFactsJsonl(text: string): EngineFact[] {
	const out: EngineFact[] = [];
	for (const line of text.split("\n")) {
		const t = line.trim();
		if (!t) continue;
		try {
			const f = JSON.parse(t);
			if (validFact(f)) out.push(f);
		} catch {
			/* skip a corrupt line — append-only file, never hard-fail */
		}
	}
	return out;
}

export function serializeFactsJsonl(facts: EngineFact[]): string {
	return facts.map((f) => JSON.stringify(f)).join("\n") + (facts.length ? "\n" : "");
}

/* ── retain ops ────────────────────────────────────────────────────────── */

/** Apply validated ops; add dedupes by canonical key (turns into an update),
 *  then prunes to MAX_ENGINE_FACTS keeping the most recently touched. */
export function applyRetainOps(
	facts: EngineFact[],
	ops: RetainOp[],
	now: number,
	genId: () => string
): { facts: EngineFact[]; added: number; updated: number; deleted: number } {
	let added = 0;
	let updated = 0;
	let deleted = 0;
	const out = [...facts];
	for (const op of ops) {
		if (op.op === "add") {
			const key = factKey(op.text);
			const dup = out.find((f) => factKey(f.text) === key);
			if (dup) {
				dup.text = op.text;
				dup.kind = op.kind;
				dup.entities = op.entities;
				dup.updatedAt = now;
				updated++;
			} else {
				out.push({
					id: genId(),
					kind: op.kind,
					text: op.text,
					entities: op.entities,
					trust: 0.5,
					createdAt: now,
					updatedAt: now,
				});
				added++;
			}
		} else if (op.op === "update") {
			const f = out.find((x) => x.id === op.id);
			if (f) {
				f.text = op.text;
				f.updatedAt = now;
				updated++;
			}
		} else if (op.op === "delete") {
			const i = out.findIndex((x) => x.id === op.id);
			if (i >= 0) {
				out.splice(i, 1);
				deleted++;
			}
		}
	}
	if (out.length > MAX_ENGINE_FACTS) {
		out.sort((a, b) => b.updatedAt - a.updatedAt);
		out.length = MAX_ENGINE_FACTS;
	}
	return { facts: out, added, updated, deleted };
}

/* ── LLM prompts ───────────────────────────────────────────────────────── */

const RETAIN_SYSTEM = [
	"You are the memory extractor for an Obsidian agent (Open Agent).",
	"Extract ONLY durable facts worth remembering across sessions: stable preferences, decisions, project state, recurring patterns, important events.",
	"Skip greetings, chit-chat, and anything transient.",
	'Classify each fact as "world" (facts about the world/project) or "experience" (things that happened in this conversation).',
	"Respond with a JSON array of operations and nothing else:",
	'[{"op":"add","kind":"world|experience","text":"…","entities":["…"]},',
	' {"op":"update","id":"<existing id>","text":"…"},',
	' {"op":"delete","id":"<existing id>"}]',
	"Rules:",
	"· add — a new fact not already covered (dedupe against the existing facts below).",
	"· update — an existing fact changed or was refined; reuse its id and give the new text.",
	"· delete — an existing fact is now wrong, obsolete, or contradicts a newer fact; delete it rather than keeping both.",
	"· entities — short proper names/keys the fact is about (optional, at most 5).",
	"· if nothing is worth remembering, return [].",
].join("\n");

export function buildRetainPrompt(
	turnText: string,
	facts: EngineFact[],
	maxInventoryChars = 8000
): { role: string; content: string }[] {
	const inventory = facts.length === 0 ? "(none yet)" : facts.map((f) => `${f.id} | ${f.kind} | ${f.text}`).join("\n");
	const capped = inventory.length > maxInventoryChars ? inventory.slice(0, maxInventoryChars) + "\n…(truncated)" : inventory;
	return [
		{ role: "system", content: RETAIN_SYSTEM },
		{ role: "user", content: `## Existing facts\n${capped}\n\n## Conversation turn\n${turnText}` },
	];
}

/** Parse a JSON array of ops out of an LLM reply (first `[…]` span). */
export function parseRetainOps(raw: string): RetainOp[] {
	if (!raw) return [];
	const start = raw.indexOf("[");
	const end = raw.lastIndexOf("]");
	if (start < 0 || end <= start) return [];
	let parsed: unknown;
	try {
		parsed = JSON.parse(raw.slice(start, end + 1));
	} catch {
		return [];
	}
	if (!Array.isArray(parsed)) return [];
	const out: RetainOp[] = [];
	for (const item of parsed) {
		if (!item || typeof item !== "object" || Array.isArray(item)) continue;
		const o = item as Record<string, unknown>;
		if (o.op === "add") {
			const text = typeof o.text === "string" ? o.text.trim().slice(0, 500) : "";
			if (!text) continue;
			const kind: FactKind = o.kind === "experience" ? "experience" : "world";
			const entities = Array.isArray(o.entities)
				? (o.entities as unknown[])
						.filter((e): e is string => typeof e === "string")
						.map((e) => e.trim())
						.filter(Boolean)
						.slice(0, 5)
				: [];
			out.push({ op: "add", kind, text, entities });
		} else if (o.op === "update") {
			const id = typeof o.id === "string" ? o.id : "";
			const text = typeof o.text === "string" ? o.text.trim().slice(0, 500) : "";
			if (!id || !text) continue;
			out.push({ op: "update", id, text });
		} else if (o.op === "delete") {
			const id = typeof o.id === "string" ? o.id : "";
			if (!id) continue;
			out.push({ op: "delete", id });
		}
	}
	return out;
}

/* ── reflect ops (Fase 2) ──────────────────────────────────────────────── */

export type ReflectOp =
	| { op: "obs"; text: string; factIds: string[]; proofs: string[]; replaceId?: string }
	| { op: "obsDelete"; id: string }
	| { op: "model"; question: string; answer: string };

/** Reflect cadence: consolidate when enough facts exist and enough have
 *  accumulated since the last pass (or a cooldown elapsed with new facts). */
export function consolidationDue(facts: EngineFact[], meta: EngineMeta | null, now: number): boolean {
	if (facts.length === 0) return false;
	if (!meta) return facts.length >= 8;
	const dirty = facts.length - meta.factCountAtReflect;
	if (dirty <= 0) return false;
	if (dirty >= 5) return true;
	return now - (meta.lastReflectAt ?? 0) > 10 * 60_000;
}

const REFLECT_SYSTEM = [
	"You are the memory consolidator for an Obsidian agent (Open Agent).",
	"Consolidate related facts into observations — deduplicated, evidence-backed beliefs.",
	"An observation keeps its supporting evidence: the exact quotes (proofs) and the fact ids it is grounded in.",
	"Rules:",
	"· group RELATED facts into one observation; do not emit one observation per fact.",
	"· when new facts extend or change an existing observation, refine it with replaceId — never create a duplicate.",
	"· do not delete facts — they are the evidence. Only delete an observation that facts no longer support.",
	"· answer each mental-model question from the observations; skip a question when there is not enough signal.",
	"Respond with a JSON array and nothing else:",
	'[{"op":"obs","text":"…","factIds":["f-…"],"proofs":["exact quote"],"replaceId":"o-…"},',
	' {"op":"obsDelete","id":"o-…"},',
	' {"op":"model","question":"…","answer":"…"}]',
].join("\n");

export function buildReflectPrompt(
	facts: EngineFact[],
	observations: EngineObservation[],
	models: EngineMentalModel[]
): { role: string; content: string }[] {
	const factsBlock = facts.length ? facts.map((f) => `${f.id} | ${f.kind} | ${f.text}`).join("\n") : "(none)";
	const obsBlock = observations.length ? observations.map((o) => `${o.id} | ${o.text}`).join("\n") : "(none)";
	const questionsBlock = MENTAL_MODEL_QUESTIONS.map((q) => {
		const cur = models.find((m) => m.question === q);
		return `Q: ${q}\nCurrent answer: ${cur ? cur.answer : "(none yet)"}`;
	}).join("\n\n");
	return [
		{ role: "system", content: REFLECT_SYSTEM },
		{
			role: "user",
			content: `## Facts\n${factsBlock}\n\n## Existing observations\n${obsBlock}\n\n## Mental-model questions\n${questionsBlock}`,
		},
	];
}

export function parseReflectOps(raw: string): ReflectOp[] {
	if (!raw) return [];
	const start = raw.indexOf("[");
	const end = raw.lastIndexOf("]");
	if (start < 0 || end <= start) return [];
	let parsed: unknown;
	try {
		parsed = JSON.parse(raw.slice(start, end + 1));
	} catch {
		return [];
	}
	if (!Array.isArray(parsed)) return [];
	const out: ReflectOp[] = [];
	for (const item of parsed) {
		if (!item || typeof item !== "object" || Array.isArray(item)) continue;
		const o = item as Record<string, unknown>;
		if (o.op === "obs") {
			const text = typeof o.text === "string" ? o.text.trim().slice(0, 500) : "";
			if (!text) continue;
			const factIds = Array.isArray(o.factIds)
				? (o.factIds as unknown[]).filter((x): x is string => typeof x === "string").slice(0, 50)
				: [];
			const proofs = Array.isArray(o.proofs)
				? (o.proofs as unknown[]).filter((x): x is string => typeof x === "string").map((x) => x.slice(0, 300)).slice(0, 50)
				: [];
			const replaceId = typeof o.replaceId === "string" && o.replaceId ? o.replaceId : undefined;
			out.push({ op: "obs", text, factIds, proofs, replaceId });
		} else if (o.op === "obsDelete") {
			const id = typeof o.id === "string" ? o.id : "";
			if (!id) continue;
			out.push({ op: "obsDelete", id });
		} else if (o.op === "model") {
			const question = typeof o.question === "string" ? o.question.trim() : "";
			const answer = typeof o.answer === "string" ? o.answer.trim().slice(0, 1000) : "";
			if (!question || !answer) continue;
			if (!MENTAL_MODEL_QUESTIONS.includes(question)) continue; // bounded, read-cheap set
			out.push({ op: "model", question, answer });
		}
	}
	return out;
}

export function applyReflectOps(
	observations: EngineObservation[],
	models: EngineMentalModel[],
	ops: ReflectOp[],
	now: number,
	genId: (prefix: string) => string
): { observations: EngineObservation[]; models: EngineMentalModel[]; obsAdded: number; obsUpdated: number; obsDeleted: number; modelsUpdated: number } {
	const obs = [...observations];
	const mods = [...models];
	let obsAdded = 0;
	let obsUpdated = 0;
	let obsDeleted = 0;
	let modelsUpdated = 0;
	for (const op of ops) {
		if (op.op === "obs") {
			const existing = op.replaceId ? obs.find((x) => x.id === op.replaceId) : undefined;
			if (existing) {
				existing.text = op.text;
				existing.factIds = [...new Set([...existing.factIds, ...op.factIds])];
				existing.proofs = [...new Set([...existing.proofs, ...op.proofs])].slice(0, 50);
				existing.proofCount = existing.factIds.length;
				existing.updatedAt = now;
				obsUpdated++;
			} else {
				obs.push({
					id: genId("o"),
					text: op.text,
					factIds: op.factIds,
					proofs: op.proofs.slice(0, 50),
					proofCount: op.factIds.length,
					trust: 0.5,
					createdAt: now,
					updatedAt: now,
				});
				obsAdded++;
			}
		} else if (op.op === "obsDelete") {
			const i = obs.findIndex((x) => x.id === op.id);
			if (i >= 0) {
				obs.splice(i, 1);
				obsDeleted++;
			}
		} else if (op.op === "model") {
			const existing = mods.find((m) => m.question === op.question);
			if (existing) {
				existing.answer = op.answer;
				existing.updatedAt = now;
			} else {
				mods.push({ id: genId("m"), question: op.question, answer: op.answer, updatedAt: now });
			}
			modelsUpdated++;
		}
	}
	if (obs.length > MAX_ENGINE_OBSERVATIONS) {
		obs.sort((a, b) => b.updatedAt - a.updatedAt);
		obs.length = MAX_ENGINE_OBSERVATIONS;
	}
	if (mods.length > MAX_ENGINE_MODELS) {
		mods.sort((a, b) => b.updatedAt - a.updatedAt);
		mods.length = MAX_ENGINE_MODELS;
	}
	return { observations: obs, models: mods, obsAdded, obsUpdated, obsDeleted, modelsUpdated };
}

/* ── mental model block (read-cheap, no LLM) ───────────────────────────── */

export function buildMentalModelBlock(models: EngineMentalModel[], maxChars = 1500): string | null {
	const withAnswers = models.filter((m) => m.answer.trim().length > 0);
	if (withAnswers.length === 0) return null;
	let body = "";
	for (const m of withAnswers) {
		const line = `- ${m.question} → ${m.answer}`;
		if (body.length + line.length + 1 > maxChars) break;
		body += (body ? "\n" : "") + line;
	}
	if (!body) return null;
	return `Mental models (settled knowledge from memory):\n${body}`;
}

/* ── observations / models / meta JSONL ────────────────────────────────── */

function validObservation(o: unknown): o is EngineObservation {
	if (!o || typeof o !== "object" || Array.isArray(o)) return false;
	const r = o as Record<string, unknown>;
	return (
		typeof r.id === "string" &&
		typeof r.text === "string" &&
		r.text.trim().length > 0 &&
		Array.isArray(r.factIds) &&
		Array.isArray(r.proofs) &&
		typeof r.proofCount === "number" &&
		typeof r.trust === "number" &&
		typeof r.createdAt === "number" &&
		typeof r.updatedAt === "number"
	);
}

function validMentalModel(m: unknown): m is EngineMentalModel {
	if (!m || typeof m !== "object" || Array.isArray(m)) return false;
	const r = m as Record<string, unknown>;
	return typeof r.id === "string" && typeof r.question === "string" && typeof r.answer === "string" && typeof r.updatedAt === "number";
}

function parseJsonl<T>(text: string, valid: (x: unknown) => x is T): T[] {
	const out: T[] = [];
	for (const line of text.split("\n")) {
		const t = line.trim();
		if (!t) continue;
		try {
			const v = JSON.parse(t);
			if (valid(v)) out.push(v);
		} catch {
			/* skip corrupt lines */
		}
	}
	return out;
}

export function parseObservationsJsonl(text: string): EngineObservation[] {
	return parseJsonl(text, validObservation);
}

export function parseModelsJsonl(text: string): EngineMentalModel[] {
	return parseJsonl(text, validMentalModel);
}

export function serializeObservationsJsonl(obs: EngineObservation[]): string {
	return obs.map((o) => JSON.stringify(o)).join("\n") + (obs.length ? "\n" : "");
}

export function serializeModelsJsonl(models: EngineMentalModel[]): string {
	return models.map((m) => JSON.stringify(m)).join("\n") + (models.length ? "\n" : "");
}

export function parseMeta(text: string): EngineMeta | null {
	if (!text) return null;
	try {
		const o = JSON.parse(text) as Record<string, unknown>;
		if (typeof o.lastReflectAt !== "number" || typeof o.factCountAtReflect !== "number") return null;
		return { lastReflectAt: o.lastReflectAt, factCountAtReflect: o.factCountAtReflect };
	} catch {
		return null;
	}
}

export function serializeMeta(meta: EngineMeta): string {
	return JSON.stringify(meta);
}

/* ── recall injection ──────────────────────────────────────────────────── */

export const RECALL_PREAMBLE =
	"# Persistent memory (recalled for this message)\n" +
	"Use this to answer questions about the user and prior sessions. Do not call tools to look up information that is already present here.";

/** Facts that survive the injection scan (threatPatterns, same as MEMORY.md). */
export function recallableFacts(facts: EngineFact[]): EngineFact[] {
	return facts.filter((f) => !firstThreatMessage(f.text));
}

/** Format the injected block; null when nothing survives the scan/cap.
 *  v0.1.178: also lists consolidated observations under their own header. */
export function buildRecallBlock(
	facts: EngineFact[],
	observations: EngineObservation[] = [],
	maxChars = 3000
): string | null {
	const cleanF = facts.filter((f) => !firstThreatMessage(f.text));
	const cleanO = observations.filter((o) => !firstThreatMessage(o.text));
	if (cleanF.length === 0 && cleanO.length === 0) return null;
	const lines: string[] = [];
	for (const f of cleanF) lines.push(`- ${f.text}`);
	if (cleanO.length > 0) {
		lines.push("Consolidated observations:");
		for (const o of cleanO) lines.push(`- ${o.text}`);
	}
	let body = "";
	for (const line of lines) {
		if (body.length + line.length + 1 > maxChars) break;
		body += (body ? "\n" : "") + line;
	}
	if (!body) return null;
	return `${RECALL_PREAMBLE}\n\n${body}`;
}

/* ── vault store ───────────────────────────────────────────────────────── */

export class EngineMemoryStore {
	private folder: string;
	private seq = 0;

	constructor(
		private app: App,
		folder: string,
		private now: () => number = () => Date.now()
	) {
		this.folder = canonicalVaultPath(folder, { label: "Managed memory folder" });
	}

	setFolder(folder: string): void {
		this.folder = canonicalVaultPath(folder, { label: "Managed memory folder" });
	}

	get currentFolder(): string {
		return this.folder;
	}

	private factsPath(): string {
		const p = canonicalVaultPath(`${this.folder}/.engine/facts.jsonl`, { label: "Engine memory file" });
		if (!pathContains(this.folder, p)) throw new Error("Engine memory path escaped its folder.");
		return p;
	}

	private enginePath(fileName: string): string {
		const p = canonicalVaultPath(`${this.folder}/.engine/${fileName}`, { label: "Engine memory file" });
		if (!pathContains(this.folder, p)) throw new Error("Engine memory path escaped its folder.");
		return p;
	}

	private async readFile(path: string): Promise<string> {
		try {
			if (!(await this.app.vault.adapter.exists(path))) return "";
			return await this.app.vault.adapter.read(path);
		} catch {
			return "";
		}
	}

	async load(): Promise<EngineFact[]> {
		return parseFactsJsonl(await this.readFile(this.factsPath()));
	}

	async loadObservations(): Promise<EngineObservation[]> {
		return parseObservationsJsonl(await this.readFile(this.enginePath("observations.jsonl")));
	}

	async loadModels(): Promise<EngineMentalModel[]> {
		return parseModelsJsonl(await this.readFile(this.enginePath("models.jsonl")));
	}

	async loadMeta(): Promise<EngineMeta | null> {
		return parseMeta(await this.readFile(this.enginePath("meta.json")));
	}

	/** Fusion recall (BM25 + entity + temporal + trust); when `embed` is
	 *  provided, candidates are re-ranked with cosine similarity (Fase 3).
	 *  No LLM in either path — embedding is optional and injected. */
	async search(query: string, limit = 8, embed?: EmbedFn): Promise<EngineFact[]> {
		let ranked = rankFacts(query, await this.load(), this.now(), Math.max(limit * 3, 20));
		if (embed) ranked = await fuseScores(query, ranked, (r) => r.fact.text, embed);
		return ranked.slice(0, limit).map((r) => r.fact);
	}

	/** v0.1.178: consolidated observations recalled the same fused way. */
	async searchObservations(query: string, limit = 4, embed?: EmbedFn): Promise<EngineObservation[]> {
		let ranked = rankObservations(query, await this.loadObservations(), this.now(), Math.max(limit * 3, 12));
		if (embed) ranked = await fuseScores(query, ranked, (r) => r.obs.text, embed);
		return ranked.slice(0, limit).map((r) => r.obs);
	}

	/** One LLM call distills a turn into typed ops, then persists. */
	async retain(
		turnText: string,
		llm: EngineLLM,
		opts: { signal?: AbortSignal; maxInventoryChars?: number } = {}
	): Promise<RetainCounts> {
		const facts = await this.load();
		const messages = buildRetainPrompt(turnText, facts, opts.maxInventoryChars);
		const raw = await llm(messages, opts.signal);
		const ops = parseRetainOps(raw);
		if (ops.length === 0) return { added: 0, updated: 0, deleted: 0 };
		const result = applyRetainOps(facts, ops, this.now(), () => this.genId("f"));
		await this.writeFile(this.factsPath(), serializeFactsJsonl(result.facts));
		return { added: result.added, updated: result.updated, deleted: result.deleted };
	}

	/** Fase 2: one LLM call consolidates facts → observations and answers the
	 *  standing mental-model questions. Silent on any failure (best-effort). */
	async reflect(
		llm: EngineLLM,
		opts: { signal?: AbortSignal } = {}
	): Promise<{ obsAdded: number; obsUpdated: number; obsDeleted: number; modelsUpdated: number } | null> {
		const [facts, observations, models, meta] = await Promise.all([
			this.load(),
			this.loadObservations(),
			this.loadModels(),
			this.loadMeta(),
		]);
		const now = this.now();
		if (!consolidationDue(facts, meta, now)) return null;
		const messages = buildReflectPrompt(facts, observations, models);
		const raw = await llm(messages, opts.signal);
		const ops = parseReflectOps(raw);
		if (ops.length === 0) {
			/* still mark the pass so a silent "[]" doesn't re-fire every turn */
			await this.writeFile(this.enginePath("meta.json"), serializeMeta({ lastReflectAt: now, factCountAtReflect: facts.length }));
			return { obsAdded: 0, obsUpdated: 0, obsDeleted: 0, modelsUpdated: 0 };
		}
		const result = applyReflectOps(observations, models, ops, now, (p) => this.genId(p));
		await this.writeFile(this.enginePath("observations.jsonl"), serializeObservationsJsonl(result.observations));
		await this.writeFile(this.enginePath("models.jsonl"), serializeModelsJsonl(result.models));
		await this.writeFile(this.enginePath("meta.json"), serializeMeta({ lastReflectAt: now, factCountAtReflect: facts.length }));
		return {
			obsAdded: result.obsAdded,
			obsUpdated: result.obsUpdated,
			obsDeleted: result.obsDeleted,
			modelsUpdated: result.modelsUpdated,
		};
	}

	/** Settled knowledge, read straight from disk — no LLM at retrieval time. */
	async mentalModelsBlock(maxChars = 1500): Promise<string | null> {
		return buildMentalModelBlock(await this.loadModels(), maxChars);
	}

	private genId(prefix: string): string {
		this.seq = (this.seq + 1) % 46656;
		return `${prefix}-${this.now().toString(36)}-${this.seq.toString(36)}`;
	}

	private async writeFile(path: string, text: string): Promise<void> {
		const dir = path.split("/").slice(0, -1).join("/");
		if (dir) await this.app.vault.adapter.mkdir(dir).catch(() => {});
		await this.app.vault.adapter.write(path, text);
	}
}
